name: Example Required Workflow 2
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: policy-enforce-pr-2
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
    
